# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Next.js app to Azure Web App - MonitorControl

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js version
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: npm install, build, and test
      env:
        SMTP_USER: ${{ secrets.SMTP_USER }}
        SMTP_PASS: ${{ secrets.SMTP_PASS }}
      run: |
        npm ci
        npm run build
        npm run export || echo "Export command not found, skipping"
      working-directory: .

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: node-app
        path: |
          package.json
          package-lock.json
          next.config.js
          public/
          .next/
          node_modules/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Production
      url: https://monitorcontrol.azurewebsites.net
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout
  
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6B933868BE184498B1F50DA35BADFD2C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_757E76214E4B4B9C8A7AF4166149014C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C341306414E84525AE430ED5DF04817F }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'MonitorControl'
          slot-name: 'Production'
          package: .